import { z } from 'zod';
export const profileSchema = z.object({name:z.string().trim().min(1).max(40),age:z.number().int().min(18).max(100),sex:z.enum(['male','female','unspecified']),height:z.number().min(120).max(230),weight:z.number().min(40).max(250),goal:z.enum(['lose','maintain','gain']),training:z.number().int().min(0).max(7),activity:z.enum(['low','moderate','high']),difficulty:z.enum(['gentle','balanced','focused']),alcoholFrequency:z.number().int().min(0).max(7),start:z.iso.date(),timezone:z.string().max(80),targetWeight:z.number().min(40).max(250).nullable(),waist:z.number().min(40).max(200).nullable(),calorieLow:z.number().min(1200).max(6000).nullable(),calorieHigh:z.number().min(1200).max(6500).nullable(),protein:z.number().min(40).max(300).nullable(),share:z.boolean(),minimum:z.string().max(300),reviewReminder:z.boolean()}).refine(p=>p.calorieLow===null||p.calorieHigh===null||p.calorieLow<=p.calorieHigh,'Target range must be ordered');
export type Profile=z.infer<typeof profileSchema>;
export const itemSchema=z.object({name:z.string().min(1).max(120),quantity:z.string().max(80),caloriesLow:z.number().min(0).max(20000),caloriesHigh:z.number().min(0).max(20000),proteinLow:z.number().min(0).max(600),proteinHigh:z.number().min(0).max(600),standardDrinks:z.number().min(0).max(100)});
export const estimateBase=z.object({foods:z.array(itemSchema).max(40),drinks:z.array(itemSchema).max(40),exercise:z.array(z.string().max(100)).max(10),steps:z.number().int().min(0).max(100000).nullable(),confidence:z.enum(['low','medium','high']),assumptions:z.array(z.string().max(240)).max(8),clarification:z.string().max(180).nullable(),safetyConcern:z.boolean(),completeDay:z.boolean()});
export const estimateSchema=estimateBase.superRefine((e,c)=>{for(const i of [...e.foods,...e.drinks])if(i.caloriesLow>i.caloriesHigh||i.proteinLow>i.proteinHigh)c.addIssue({code:'custom',message:'Invalid estimate range'});});
export type Estimate=z.infer<typeof estimateSchema>;
export type Entry={id:string;day:string;estimate:Estimate;source:'voice'|'text'|'memory';};
export const fastSchema=z.object({food:z.enum(['on','off']),training:z.enum(['done','rest','missed']),alcohol:z.enum(['none','planned','unplanned']),complete:z.boolean(),minimum:z.boolean()});
export type Fast=z.infer<typeof fastSchema>;
export function targets(p:Profile){const bmr=10*p.weight+6.25*p.height-5*p.age+(p.sex==='male'?5:p.sex==='female'?-161:-78);const tdee=bmr*({low:1.35,moderate:1.55,high:1.75}[p.activity]);const shift=p.goal==='lose'?-Math.min(350,tdee*.15):p.goal==='gain'?200:0;const floor=Math.max(1200,bmr);const mid=tdee+shift;return {bmr:Math.round(bmr),tdee:Math.round(tdee),low:Math.round(Math.max(floor,p.calorieLow??mid-150)),high:Math.round(Math.max(floor+100,p.calorieHigh??mid+150)),protein:Math.round(p.protein??p.weight*1.6),maintenanceLow:Math.round(tdee*.9),maintenanceHigh:Math.round(tdee*1.1)};}
export function mergeEntries(entries:Entry[]){const unique=[...new Map(entries.map(e=>[e.id,e])).values()];const items=unique.flatMap(e=>[...e.estimate.foods,...e.estimate.drinks]);return {caloriesLow:items.reduce((s,i)=>s+i.caloriesLow,0),caloriesHigh:items.reduce((s,i)=>s+i.caloriesHigh,0),proteinLow:items.reduce((s,i)=>s+i.proteinLow,0),proteinHigh:items.reduce((s,i)=>s+i.proteinHigh,0),drinks:items.reduce((s,i)=>s+i.standardDrinks,0),steps:Math.max(0,...unique.map(e=>e.estimate.steps??0)),exercise:[...new Set(unique.flatMap(e=>e.estimate.exercise))],complete:unique.some(e=>e.estimate.completeDay),unsafe:unique.some(e=>e.estimate.safetyConcern)};}
export function score(f:Fast,gold=false,unsafe=false){const nutrition=unsafe?0:f.food==='on'||gold?35:0;const training=f.training==='missed'?0:25;const alcohol=f.alcohol==='unplanned'?0:25;const consistency=f.complete?15:0;return {total:nutrition+training+alcohol+consistency,nutrition,training,alcohol,consistency,status:gold?'Gold':nutrition===35&&alcohol===25?'Green':'Off-plan'};}
export function dayScore(f:Fast,entries:Entry[],p:Profile,gold=false){const total=mergeEntries(entries);const t=targets(p);const under=total.complete&&entries.length>0&&total.caloriesHigh<t.low*.75;return score(f,gold,total.unsafe||under);}
export function dateInZone(zone='Australia/Sydney',now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function dayDiff(a:string,b:string){return Math.round((Date.parse(a+'T12:00:00Z')-Date.parse(b+'T12:00:00Z'))/86400000);}
export function weekDays(day:string){const d=new Date(day+'T12:00:00Z');const monday=(d.getUTCDay()+6)%7;return Array.from({length:7},(_,i)=>new Date(d.getTime()+(i-monday)*86400000).toISOString().slice(0,10));}
export function weeklyEnergy(entries:Entry[],p:Profile,day:string){const days=weekDays(day).filter(d=>d<=day);const complete=days.filter(d=>mergeEntries(entries.filter(e=>e.day===d)).complete);const sums=mergeEntries(entries.filter(e=>complete.includes(e.day)));const t=targets(p);return {loggedDays:complete.length,elapsedDays:days.length,intakeLow:sums.caloriesLow,intakeHigh:sums.caloriesHigh,positionLow:complete.length*t.low-sums.caloriesHigh,positionHigh:complete.length*t.high-sums.caloriesLow,weeklyLow:t.low*7,weeklyHigh:t.high*7};}
export type Weight={day:string;weight:number};
export function weightTrend(weights:Weight[]){const sorted=[...weights].sort((a,b)=>a.day.localeCompare(b.day));return sorted.map(w=>{const window=sorted.filter(x=>dayDiff(w.day,x.day)>=0&&dayDiff(w.day,x.day)<7);return {...w,average:window.reduce((s,x)=>s+x.weight,0)/window.length};});}
export function trajectory(weights:Weight[],start:string,today:string){const trend=weightTrend(weights);const recent=trend.filter(w=>dayDiff(today,w.day)<=28);if(recent.length<4||dayDiff(recent.at(-1)!.day,recent[0].day)<14)return null;const first=recent[0],last=recent.at(-1)!;const rate=(last.average-first.average)/dayDiff(last.day,first.day);if(Math.abs(rate*7)>last.average*.01)return null;const left=Math.max(0,90-dayDiff(today,start));const projected=last.average+rate*left;const uncertainty=Math.max(.5,left*.025);return {low:projected-uncertainty,high:projected+uncertainty,current:last.average};}
export const safeMessage='Return to normal meals, hydrate, and keep movement comfortable. No fasting, purging or extra workouts to compensate. If this feels hard to manage, speak with a qualified health professional.';
export function unsafeText(text:string){return /purge|purging|starv|punish.{0,20}(exercise|workout)|throw.{0,8}up|vomit.{0,12}(food|meal)|fast.{0,25}compensat|burn.{0,15}off.{0,15}(meal|food|drink)/i.test(text);}
export function standardDrinks(ml:number,abv:number){return ml*abv*.789/1000;}
export function weeklyAdherence(logs:{day:string;data:Fast}[],entries:Entry[],p:Profile,today:string,events:{day:string}[]){const elapsed=weekDays(today).filter(d=>d<=today&&d>=p.start);if(!elapsed.length)return 0;const current=logs.filter(d=>elapsed.includes(d.day));const behaviour=current.reduce((sum,d)=>{const s=dayScore(d.data,entries.filter(e=>e.day===d.day),p,events.some(e=>e.day===d.day));return sum+s.nutrition+s.alcohol+s.consistency;},0)/elapsed.length;const training=p.training===0?25:25*Math.min(1,current.filter(d=>d.data.training==='done').length/(p.training*elapsed.length/7));return Math.round(behaviour+training);}
export function streak(logs:{day:string;data:Fast}[],today:string){let cursor=logs.some(l=>l.day===today&&l.data.complete)?today:new Date(Date.parse(today+'T12:00:00Z')-86400000).toISOString().slice(0,10);let count=0;while(logs.some(l=>l.day===cursor&&l.data.complete)){count++;cursor=new Date(Date.parse(cursor+'T12:00:00Z')-86400000).toISOString().slice(0,10);}return count;}
